luminus-framework/luminus-template

src/leiningen/new/immutant.clj, src/leiningen/new/luminus.clj, src/leiningen/new/luminus/immutant/core.clj
This is pretty much modeled on the `+http-kit` profile, but exposes all the options supported by [immutant.web/run](http://immutant.org/documentation/current/apidoc/immutant.web.html#var-run) since it can take either a map or a sequence, and the keys can be either keywords or strings, so you could do something like this:
```
$ lein run port 80 virtual-host "my.host.com"
```
Presence of `-dev` among the args will trigger the use of [run-dmc](http://immutant.org/documentation/current/apidoc/immutant.web.html#var-run-dmc) instead of `run`, e.g.
```
$ lein run -dev port 3000
```
That'll fire up your browser and enable code-reloading.
=> Add +immutant profile

src/leiningen/new/luminus/core/resources/docs.md
Adding the log-request to the docs since it was removed from the middleware file on 941944b3bbfccef11cd33840b189821500594699
=> Adding log-request code to docs.md

src/leiningen/new/luminus/core/test/handler.clj
Following Clojure style guidance to require namespaces.
=> Minor changes: replacing ":use" by ":refer :all"

src/leiningen/new/luminus/db/sql/queries.sql
Normalized the 'name:' spacing and fixed a typo in get-user docstring.
=> Minor formatting of sql queries template

src/leiningen/new/luminus/core/project.clj
`ring-mock` has moved to another [repository](https://github.com/ring-clojure/ring-mock).
=> Updating ring-mock dependency

src/leiningen/new/luminus/core/project.clj, src/leiningen/new/luminus/core/src/handler.clj, src/leiningen/new/luminus/core/src/middleware.clj, src/leiningen/new/luminus/core/src/session.clj
* The new storage has a TTL based on core.cache ([project's page](https://github.com/boechat107/ring-ttl-session)).
* Downside: there is no automatic redirect for expired sessions.
=> Replacing ring's native in-memory session storage

src/leiningen/new/luminus/cljs/env/dev/cljs/app.cljs
`:jsload-callback` seems deprecated, so I just replaced it :)
https://github.com/bhauman/lein-figwheel/blob/2e1733c4a728ed74051a860be844db4580dc0177/support/src/figwheel/client.cljs#L278-L283
=> Replace deprecated js callback key

src/leiningen/new/db.clj
It's been a while since postgres is stable in 9.4
=> Change postgres library version

src/leiningen/new/luminus/cljs/src/cljs/core.cljs, src/leiningen/new/luminus/cljs/templates/home.html
this change adds the required HTML and JS changes to make sure the
navbar works on both large and small displays, collapsing into a
dropdown menu. Taken from the bootstrap example at
http://getbootstrap.com/examples/navbar-fixed-top/
=> fixes to the default cljs navbar

src/leiningen/new/cljs.clj
Very minor change.
Some settings specified in cljs.clj are the same as the default and thus redundant. See:
https://github.com/clojure/clojurescript/wiki/Compiler-Options#output-dir
https://github.com/clojure/clojurescript/wiki/Compiler-Options#optimizations
There were also some inconsistencies about the ordering of the keys.
=> deleted settings that are equal to default

src/leiningen/new/luminus/cljs/src/cljs/core.cljs
When a luminus app is deployed using a server context path other than "/" the client cannot fetch the docs, because of a missing context fetch.
=> add missing server context

src/leiningen/new/luminus/core/src/middleware.clj
IntelliJ with Cursive flags the '.getContextPath' call as an error because it
can't infer the type of a context. This is a workaround.
=> fix an annoying IDE warning

src/leiningen/new/luminus/db/src/mongodb.clj
In [monger tutorial](http://clojuremongodb.info/articles/getting_started.html), they use `_id`. (not `id`)
I also checked [mongodb documentation](http://docs.mongodb.org/manual/reference/glossary/#term-id). they introduce `_id` as primary key.
=> fix key for monger identifier

src/leiningen/new/luminus/core/resources/templates/base.html
To avoid the blink effect of displaying the HTML before applying the CSS.
I recently had to change it directly on the APP i'm coding using luminius and elasticsearch, the page to list patients would fix show a not formated HTML and then apply the CSS.
https://github.com/josedonizetti/odontoreis
=> position css at the top

src/leiningen/new/immutant.clj
As of now, when deploying luminus app to WildFly via immutant plugin, serving webjars assets does not work, and `webjars-locator-jboss-vfs` fixes it. See also https://github.com/webjars/webjars-locator/issues/18
=> add webjars-locator-jboss-vfs as dependency for immutant profile

src/leiningen/new/cljs.clj
As discussed in bhauman/lein-figwheel#286, it seems that figwheel-0.5.0
raises the error above in some circumstances. As a workaround, as
suggested in the comments, an explicit dependency to clojurescruot
1.7.170 has been added to the plugins section.
=> Workaround for "No such var: ana/forms-seq*"

README.md
As `lein-ring` isn't included in the template as far as I can tell, I removed all references to `lein ring *`.
=> Removed references to lein-ring

resources/leiningen/new/luminus/core/gitignore
```
❯ lein version                                                                                                                                    ✹
Leiningen 2.6.1 on Java 1.8.0_60 Java HotSpot(TM) 64-Bit Server VM
```
Remove space in front of .nrepl-port. It doesn't work for me (MAC OSX 10.7
=> Remove extra space in gitignore

resources/leiningen/new/luminus/core/env/dev/clj/env.clj, resources/leiningen/new/luminus/core/env/dev/clj/user.clj, resources/leiningen/new/luminus/core/env/dev/resources/config.edn, resources/leiningen/new/luminus/core/env/prod/clj/env.clj, resources/leiningen/new/luminus/core/env/test/resources/config.edn, resources/leiningen/new/luminus/core/project.clj, resources/leiningen/new/luminus/core/src/config.clj, resources/leiningen/new/luminus/core/src/core.clj, resources/leiningen/new/luminus/core/src/handler.clj, resources/leiningen/new/luminus/core/src/middleware.clj, resources/leiningen/new/luminus/db/src/migrations.clj, resources/leiningen/new/luminus/db/src/mongodb.clj, resources/leiningen/new/luminus/db/src/sql.db.clj, resources/leiningen/new/luminus/db/test/db/core.clj, src/leiningen/new/luminus.clj
replacing `lein-environ` / `luminus-config` with [cprop](https://github.com/tolitius/cprop)
* config comes from `env/dev|test|prod/resources/config.edn`
* new `<<project-ns>>.config` namespace that has a config state
* `(mount/start)` need to be called on `start-app` to start this config state
=> replacing environ/luminus-config with cprop

README.md
Buddy's documentation URL has been split into pieces when Buddy was made into modules. This updates the link to point to the root repository, which links to the new submodules in it's README.md which is displayed at the new URL.
=> Update +auth (Buddy) URL in README.md

resources/leiningen/new/luminus/core/project.clj
`:target-path` for generated project was not set, so the default `target/` was used, which lead to contamination (e.g. after `lein uberjar`, `lein run` used config class compiled from `env/prod/project-name/...`, not `env/dev/project-name/...`).
It this PR `:target-path` is set to include current profiles, as [recommended](https://github.com/technomancy/leiningen/blob/master/sample.project.clj) by leiningen.
=> Profile-dependent target path to avoid cross-profile contamination

project.clj
This way the user at least gets a warning when their lein is behind.
=> Specify required lein version in project.clj

resources/leiningen/new/luminus/db/src/mongodb.clj
`com.mongodb.DB cannot be cast to com.mongodb.Mongo`
=> fix problem with closing connection:

resources/leiningen/new/luminus/db/docs/db_instructions.md, resources/leiningen/new/luminus/db/docs/h2_instructions.md, resources/leiningen/new/luminus/db/docs/mongo_instructions.md
Adds a bullet point to the default instructions that appear on template versions with database integration, informing users that they need to require the db.core namespace in order to get mount to automatically connect to the database.
=> add more detail on connecting template app to databases

src/leiningen/new/cider.clj
cider-nrepl should be in :dependecies instead of :dev-plugins as it's required in core.clj.
=> :dependencies instead of :dev-plugins to bundle cider-nrepl in jar or war

resources/leiningen/new/luminus/core/src/home.clj
There was some encoding problem with non-ASCII char because the markdown file
was read as octet-stream.
Should I do the same thing for `else` branch? There is
```clojure
(layout/render
"home.html" {:docs (-> "docs/docs.md" io/resource slurp)})
```
I didn't test the encoding problem for this part.
Cheers
=> add the content-type to the /docs route

resources/leiningen/new/luminus/core/src/middleware.clj, src/leiningen/new/auth.clj, src/leiningen/new/auth_base.clj, src/leiningen/new/auth_jwe.clj, src/leiningen/new/luminus.clj
So I switched out `service` for `auth` as a dependency and updated the logic of middleware. I am not sure how to extract `['buddy.auth.backends.session :refer ['session-backend]]` with this dep setup. Any thoughts? Happy to update/tweak this as necessary...
=> Auth-jwe dependency update

src/leiningen/new/auth_jwe.clj
The clj-time version is incorrect in `auth-jwe` and causes swagger to break. My apologies for the incorrect versioning on the original pull...
=> Fixed outdated clj-time version

resources/leiningen/new/luminus/core/env/dev/resources/logback.xml, resources/leiningen/new/luminus/core/env/prod/resources/logback.xml
org.apache.http logs extremely aggressively at DEBUG. Suppress by default.
=> suppress org.apache.http verbosity

src/leiningen/new/cider.clj
The latest version of cider is now using `0.15.0-SNAPSHOT`
=> Bumped cider version

src/leiningen/new/cucumber.clj
it's related to #197
when I generated project with 
```
$ lein new luminus spike +postgres +auth-jwe +re-frame +cucumber +sassc +kibit
```
and runned project, I got:
```
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jcajce.JcaJceHelper
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```
I fixed it by adding exclusions like was defined in #197, but this was not enough
so I added additional exclusion.
```
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.crypto.digests.Blake2bDigest
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at …
```
=> problem with dependency conflict between +auth, +auth-jwe and +selenium

resources/leiningen/new/luminus/core/project.clj
Otherwise there will be unnecessary AOT, which can lead to confusing behavior.
=> Skip aot on :main in project.clj.

src/leiningen/new/luminus.clj
* fixes https://github.com/metosin/muuntaja/issues/39 (msgpack dependency spill)
=> Update Muuntaja to 0.2.1

src/leiningen/new/auth_jwe.clj
First of all, thanks for this project, you are doing a great work.
Since clj-time was added to the core dependencies, this is not needed anymore. When generating with +auth-jwe option, it was added to dependencies twice and with different version.
=> Remove time dependency from auth-jwe

src/leiningen/new/oauth.clj
The oauth environment variables were not being generated in env/dev/resources/config.edn and env/prod/resources/config.edn. Added a key to options that will trigger the generation.
=> Added :oauth key to options

README.md, resources/leiningen/new/luminus/cljs/templates/home.html, resources/leiningen/new/luminus/core/README.md, resources/leiningen/new/luminus/core/README.md.in, resources/leiningen/new/luminus/core/build.boot, resources/leiningen/new/luminus/core/src/core.clj, src/leiningen/new/boot.clj, src/leiningen/new/cljs.clj, src/leiningen/new/common.clj, src/leiningen/new/cucumber.clj, src/leiningen/new/kibit.clj, src/leiningen/new/lein.clj, src/leiningen/new/luminus.clj, src/leiningen/new/sassc.clj, src/leiningen/new/war.clj
Fixes #223.
To initiate such a project use the +boot profile.
Wherever possible, the boot template uses the same data as the lein template.
For example, all dependencies are pulled from the same option in the options
map.
The +cljs profile has been tested extensively, other profiles have not been
tested as conclusively but should work fine (most simply add assets and/or
dependencies, which boot and lein treat equally). The cucumber profile will fail if attempted to use with boot, since it uses a lein-only plugin. Kibit requires manual intervention to run with boot, and does yet have a pre-packaged task.
If creating the template using lein (without the +boot) profile, there should be no difference in behavior.
=> Adds support for a luminus project built with boot, rather than lein

resources/leiningen/new/luminus/cljs/src/cljs/app.cljs.edn
Adds the app.cljs.edn file to avoid a "Template resource
'leiningen/new/luminus/cljs/src/cljs/app.cljs.edn' not found." error.
=> Adds missing file

resources/leiningen/new/luminus/cljs/test/cljs/core_test.cljs, resources/leiningen/new/luminus/core/build.boot
Fixes an issue where a reagant import was included even when the reagent profile
was not added.
Also fixes an issue with bad arguments being passed to the cljs task in the
figwheel task (causing it to fail).
=> Fix tests and boot figwheel task

resources/leiningen/new/luminus/core/env/dev/resources/logback.xml, resources/leiningen/new/luminus/core/env/prod/resources/logback.xml
Correct syntax for logback loggers should be `<appender-ref>` elements instead of `<AppenderRef>`, which does not work. This can be checked with `<configuration debug="true">`
https://logback.qos.ch/manual/configuration.html
=> Fix typos in logback.xml configuration files.

resources/leiningen/new/luminus/db/migrations/add-users-table.up.sql
TIME has no date information, TIMESTAMP contains both date and time, which makes more sense in this case, I believe.
=> Update add-users-table.up.sql to use TIMESTAMP

project.clj, resources/leiningen/new/luminus/lacinia/resources/schema.edn, resources/leiningen/new/luminus/lacinia/src/services.clj, src/leiningen/new/lacinia.clj, src/leiningen/new/luminus.clj
This pull request adds a bare-bones example of Lacinia as an available template. 
I'm not sure best practice for integration with `compojure-api`, so I simplified the endpoint, which requires a POST with a query param. 
Otherwise, it is essentially a drop-in replacement for `swagger`.
Thanks for the great template, and please let me know if there's anything that needs to be changed...
=> Added Lacinia as an available feature

resources/leiningen/new/luminus/db/sql/queries.sql
Hi!
While working through your book, I came across this small discrepancy between the wording of the HugSQL documentation metadata comments. I hope this makes the template ever so slightly better!
Cheers,
Bojan
P.S. The other variant would be to write "user" everywhere (instead of "user record"). Maybe that would be nicer?
=> Use a consistent style in HugSQL doc comments

project.clj, src/leiningen/new/cljs.clj, src/leiningen/new/cucumber.clj, src/leiningen/new/db.clj, src/leiningen/new/graphql.clj, src/leiningen/new/hoplon.clj, src/leiningen/new/luminus.clj, src/leiningen/new/oauth.clj, src/leiningen/new/re_frame.clj, src/leiningen/new/reagent.clj, src/leiningen/new/sassc.clj, src/leiningen/new/swagger.clj
This sets the generated path as a template param which can be configurable in `luminus.clj` (at this point simply set to `:default`). 
The rationale for this would be the ability to add additional profiles to the template that would allow different project structures (think Docker services, for example). 
That said, perhaps it is too much overhead, so I will defer to you if you think it is useful or not. Thanks for the great template...
=> Relative path profile - refactoring to configurable variables

resources/leiningen/new/luminus/core/src/home.clj
I noticed graphiql wasn't served when cljs was mounted, but seems like cljs apps should get graphiql too when they +graphql. One could argue you'd want to do it in the SPA but I'm not sure that's necessary, as it's definitely intended as a devtool rather than a for-public-consumption endpoint.
=> Add the graphiql endpoint when cljs is mounted

resources/leiningen/new/luminus/core/Procfile
With the latest AWS Elastic Beanstalk running supervisor 3.2 this fails - `$JVM_OPTS` is passed literally to the java command, which fails trying to load a class of that name. 
According to the [Supervisor docs](http://supervisord.org/configuration.html#environment-variables), it should use the syntax `%(ENV_JVM_OPTS)s`. However that fails too with:
> ERROR: CANT_REREAD: Format string 'env java %(ENV_JVM_OPTS)s -cp target/uberjar/myapp.jar clojure.main -m myapp.core' for 'program:application-web-1.command' contains names ('ENV_JVM_OPTS') which cannot be expanded. Available names: ENV_PATH, ENV_TERM, ENV_UPSTART_INSTANCE, ENV_UPSTART_JOB, group_name, here, host_node_name, process_num, program_name in section 'program:application-web-1' (file: '/etc/supervisor/conf.d/application.conf')
I …
=> Procfile: Remove invalid env var

resources/leiningen/new/luminus/core/src/middleware.clj
The signature is `[message]` pr `[throwable message]`; if we only send in `t` then it will be turned into `(str t)` and we loose the stacktrace & all.
=> Fix log/error to get both params it expects

src/leiningen/new/cider.clj
Application did not start with 0.15.0 because of:
java.lang.ExceptionInInitializerError >> Invalid token ::clojure.test/once-fixtures
Maybe this is related: clojure-emacs/cider#2081
=> Update cider-nrepl to 0.15.1

resources/leiningen/new/luminus/core/build.boot, resources/leiningen/new/luminus/core/src/core.clj, src/leiningen/new/boot.clj, src/leiningen/new/cljs.clj
Uses the boot migratus plugin and environ to set variables.
One can migrate by using "boot dev migratus". See "boot migratus -h" for more
information.
This should mean databases are fully supported under boot.
=> Adds migratus support for boot

resources/leiningen/new/luminus/core/build.boot, src/leiningen/new/boot.clj, src/leiningen/new/db.clj
Migratus commands can be run as with lein with something like `boot dev [ run migrate ]`.
The brackets are unfortunately necessary because of how boot does positional parameters. For now, I'm going to leave it like that. The new system with `dev-config.edn` and `test-config.edn` are now fully supported as well.
=> Support migratus with boot and remove references to boot cprop

resources/leiningen/new/luminus/core/env/dev/clj/user.clj
In `reset-db` function was used wrong key from `env`.
=> use correct key from env in `reset-db`

src/leiningen/new/cljs.clj
ClojureScript 1.10.339 depends on transit-clj version 0.8.309 and
transit-java 0.8.332. Some imported libraries (cljs-ajax, metosin/muuntaja)
depend on lower versions which override this resulting in ClojureScript
compilation errors.
=> Fix ClojureScript compilation error due to transit-java version.

resources/leiningen/new/luminus/core/src/nrepl.clj
Error on `lein uberjar`
```
java.io.FileNotFoundException: Could not locate clojure/tools/nrepl/server__init.class or clojure/tools/nrepl/server.clj on classpath., compiling:(nrepl.clj:1:1)
Exception in thread "main" java.io.FileNotFoundException: Could not locate clojure/tools/nrepl/server__init.class or clojure/tools/nrepl/server.clj on classpath., compiling:(nrepl.clj:1:1)
```
Version `2.9.12.79` was switched to use nREPL 0.4.4.
Due to [nrepl documentation](https://github.com/nrepl/nREPL#status)
```
[nrepl "0.4.0"] changes the namespaces from clojure.tools.nrepl.* to nrepl.*.
```
=> Incorrect namespace for nrepl.server

resources/leiningen/new/luminus/keeframe/src/cljs/core.cljs, resources/leiningen/new/luminus/keeframe/src/cljs/routing.cljs, resources/leiningen/new/luminus/keeframe/src/cljs/view.cljs, resources/leiningen/new/luminus/reagent/src/cljs/ajax.cljs, resources/leiningen/new/luminus/reframe/src/cljs/core.cljs, resources/leiningen/new/luminus/reframe/src/cljs/events.cljs, src/leiningen/new/kee_frame.clj, src/leiningen/new/re_frame.clj
Creating a PR to have a discussion about what this template should contain. I made some changes to illustrate what I'm thinking. See my comments in diff below.
=> Use less custom plumbing code in kee-frame template

resources/leiningen/new/luminus/core/Dockerfile
- `MAINTAINER` is deprecated
- Use `COPY` instead of `ADD`
Links:
- https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
- https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy
=> Update `Dockerfile` template

src/leiningen/new/graphql.clj
I ran lein new luminus myapp +graphql and the resulting project generated did not have a dependency on clojure/data.json in the project.clj file. I added this to the graphql template file.
I wasn't able to test this due to the complexity of getting a local jar build of the lein-template to be used on my system instead of the one installed from maven.
=> Adding missing dependency on org.clojure/data.json

resources/leiningen/new/luminus/core/src/middleware.clj
not sure about this one.... what i was thinking is that the entire joda lib is not being used any more, right?... so therefore there should be no import on it.... also it seams to me, that this import is not being used, which would be good, since joda is not listed in the project deps anymore,.... so i guess really this should result in a some sort of compiler warning? ( my setup does not actually do that )..... in aaany case,... i thought it would be alright to remove this part without actually breaking something..... 
also note that now it seams that the import clause might end up empty altogether.... so i thought maybe i should move the if structures of the template around a bit... but that got me confused also.... :)
so anyways.... do with this pr what you see fit... cheers :)
=> not importing from joda.time

resources/leiningen/new/luminus/core/Dockerfile
Since `java` images are deprecated (see https://hub.docker.com/_/java/)
=> Use `openjdk` docker image instead of `java`

resources/leiningen/new/luminus/core/test/handler.clj
`+swagger` seems to default to compojure-api, and the new tests are for reitit only. 
(used the template with `+swagger +kee-frame` which adds reitit behind the scenes).
=> Service tests only for reitit, not swagger (which uses c-api by default)

src/leiningen/new/db.clj
Small PR to update guava for +mongo and let uberjar compile successfully
=> update guava for mongo to 27.0.1-jre

src/leiningen/new/cljs.clj
**Problem:**
On a freshly generated Leiningen template which included cljs, I noticed starting Figwheel and the corresponding cljs repl caused the following output:
```
Figwheel: Starting server at http://0.0.0.0:3449
Figwheel: Watching build - app
Compiling build :app to "target/cljsbuild/public/js/app.js" from ["src/cljs" "src/cljc" "env/dev/cljs"]...
Successfully compiled build :app to "target/cljsbuild/public/js/app.js" in 1.062 seconds.
Figwheel: Starting CSS Watcher for paths  ["resources/public/css"]
Figwheel: Starting nREPL server on port: 7002
WARNING: unable to load "cider/wrap-cljs-repl" middleware
...
```
**Solution**
- After some digging, it doesn't seem like `cider/wrap-cljs-repl` is a valid namespace or function, and looks superfluous alongside …
=> [Fix]: Remove Unneeded call to cider/wrap-cljs-repl

resources/leiningen/new/luminus/core/env/dev/resources/logback.xml
Set the scan attribute to "true" with a scanPeriod of 10 seconds so
logging parameters can be dinamically altered during development.
=> Added scan attribute to env/dev/resources/logback.xml

resources/leiningen/new/luminus/db/src/datomic.clj
1. As mentioned at https://github.com/luminus-framework/luminus-template/issues/415
Given that in datomic, `create-database` is idempotent operation, change to
`:start (do (-> env :database-url d/create-database)(-> env :database-url d/connect))`
2. Fix original `add-user` function
3. Change schema to show how to use `db.unique/identity`
4. Remove original utility function `entity`
Remove original utility funciton `touch`
Remote original interface function `find-user`
I opinionately consider the original example functions are not very
idiomatic style to use Datomic.
5. Add my version interface function `find-user`
The first argument is database instead of connection.
6. Add function `show-transaction` to demonstrate how to use `datomic.api/tx-range`
and `datomic.api/log`
7. Add function …
=> Improve +datomic option

resources/leiningen/new/luminus/db/migrations/schema.edn, resources/leiningen/new/luminus/db/src/datomic.clj, src/leiningen/new/db.clj
1. Add datomic migration library `conformity`
2. Change original datomic example to be a more realistic schema.  (Now, this schema has database enumeration.)
=> Add datomic db migration library 'conformity

resources/leiningen/new/luminus/db/src/datomic.clj
In rational development situation, I believe that developer will change `migrations/schema.edn` again and again. Everytime the developer changes the `migrations/schema.edn`, he will re-run the function `(install-schema conn)` and will expect that the new added schema is loaded and installed. 
In original design, the developer needs to first evaluate `norms-map` and then evaluate `(install-schema conn)`, which is not a succinct development flow.
=> in +datomic option, let db.core/install-schema to re-read resource

resources/leiningen/new/luminus/core/src/handler.clj
refs: https://github.com/luminus-framework/luminus-template/issues/427
=> fix a bug in which having no env.clj file would crash the system

resources/leiningen/new/luminus/core/src/exception.clj, resources/leiningen/new/luminus/reitit/src/services.clj, src/leiningen/new/luminus.clj
all exceptions in api  intercepted by original exception-middleware, when an exception occurs, the developer can not know what happened, so i wrap the exception-middleware to log the exception.
#429
=> log stack-traces for all exceptions

src/leiningen/new/reitit.clj
Fixes a really bad bug with [bleeding path parameters](https://github.com/metosin/reitit/blob/master/CHANGELOG.md#035-2019-05-22).
=> update reitit to 0.3.5

resources/leiningen/new/luminus/keeframe/src/cljs/view.cljs, resources/leiningen/new/luminus/reagent/src/cljs/core.cljs
Hi,
the navigation does not show the currently active page correctly, this seems to fix it.
T
=> fix navigation, use class attr instead of active

src/leiningen/new/db.clj
Since the $USER is the usual person that ran `createdb`, this should reduce some friction on new project setup/startup.
=> build: make $USER the default user for databases

resources/leiningen/new/luminus/reitit/src/exception.clj, src/leiningen/new/luminus.clj
Hi Dmitri,
As discussed in Slack. Let me know if this is satisfactory.
Results in validation messages like this:
Kind regards,
Erwin
=> Human-optimized messages from clojure.spec validation errors

.gitignore, project.clj, resources/leiningen/new/luminus/core/env/dev/clj/user.clj, resources/leiningen/new/luminus/core/project.clj, resources/leiningen/new/luminus/core/src/layout.clj, resources/leiningen/new/luminus/core/src/middleware.clj, resources/leiningen/new/luminus/db/src/sql.db.clj, resources/leiningen/new/luminus/db/test/db/core.clj, resources/leiningen/new/luminus/reitit/src/home.clj, src/leiningen/new/luminus.clj, test/test_templates.clj
This introduces a single test that iterates through each of the available Luminus command line flags, creating a project with each flag enabled, then linting it.
Note that it doesn't test the `+boot` flag, as the tests are currently Leiningen-only.
```
[;; Don't test +boot, as this smoke-test only works w/ Leiningen right now.
;; "+boot"
```
It also disables the linter specifically for missing `ns` forms when dealing with Cucumber steps, because there's no way to disable linters [just for the step definitions](https://github.com/jonase/eastwood/issues/165).
Fixes #447.
=> Fix Linter warnings

resources/leiningen/new/luminus/reframe/src/cljs/core.cljs
This removes some code that is no longer used. At least I think it's not used? It looks like the router now keeps track of the page to fn mapping.
=> Remove unused code in re-frame profile

src/leiningen/new/shadow_cljs.clj
With the previous explicit dependencies
```clojure
['com.google.javascript/closure-compiler-unshaded "v20190618" :scope "provided"]
['org.clojure/google-closure-library "0.0-20190213-2033d5d9" :scope "provided"]
```
requiring an NPM package via `(:require ["package-name"])` causes shadow-cljs to throw confusing exceptions like:
```
IllegalArgumentException: No matching field found: getSourceName for class com.google.javascript.jscomp.JSError
```
which is seen discussed at https://clojurians-log.clojureverse.org/shadow-cljs/2020-01-06/1578325220.333700.
This PR fixes that by updating the Closure dependencies.
The PR also bumps the versions of shadow-cljs and core.async; if that's unwanted we can undo it.
=> Fix shadow-cljs build error caused by dependency conflicts

resources/leiningen/new/luminus/calva/client.code-workspace, resources/leiningen/new/luminus/calva/custom-commands-fragment.json, resources/leiningen/new/luminus/calva/figwheel-settings.json, resources/leiningen/new/luminus/calva/server-connect-sequence-fragment.json, resources/leiningen/new/luminus/calva/server-only-settings.json, resources/leiningen/new/luminus/calva/server.code-workspace, src/leiningen/new/calva.clj, src/leiningen/new/luminus.clj
This adds Calva settings for easier **start hacking** for these scenarios:
- Server only
- Server + shadow
- Server + figwheel
With these settings the story can be told like so:
[Luminus](https://luminusweb.com) is a powerful and versitle Leiningen template for creating web development projects. It comes with built in configuration for making it easy to use Calva as your Clojure(Script) editor. Here are the steps involved.
The workflow here is really just: Jack-in and start hacking. The first time it involves these steps, however:
0. If you haven't created the project yet, create a new server only Luminus project. For a all-defaults setup it is like so:
```sh
$ lein new luminus my-luminus-server
```
0. This creates the folder `my-luminus-server`. Open it in VS Code:
```sh
$ code …
```
=> Add Calva configurations

resources/leiningen/new/luminus/calva/figwheel-settings.json
This makes the template's included Calva settings for Figwheel promote the 127.0.0.1 interface instead of 0.0.0.0, which [doesn't work on WSL 1](https://www.reddit.com/r/Clojure/comments/fj1rbi/how_to_use_calva_with_luminus/fkxqj5c?utm_source=share&utm_medium=web2x)
=> Fix Calva settings for Figwheel to use 127.0.0.1

README.md
kttp-kit.org appears to be parked
=> Fix HTTP Kit home page URL

resources/leiningen/new/luminus/expanded/resources/docs.md
Hi,
After using this template, I noticed that some links refering to the documentation were dead. I updated them to link to what I suspect is the current documentation.
I Hope that's enough explanation.
Cheers.
=> Update documentation links in home page.

README.md
[Referenced issue](https://github.com/luminus-framework/luminus-template/issues/492#issuecomment-655592787)
=> Update README - Undertow is now the default

resources/leiningen/new/luminus/db/test/db/core.clj
>== Linting app.test.db.core ==
>test/clj/app/test/db/core.clj:22:15: wrong-arity: Function on var #'app.db.core/create-user! called with 2 args, but it is only known to take one of the following args: []  [params]  [db params options & command-options]
>test/clj/app/test/db/core.clj:37:13: wrong-arity: Function on var #'app.db.core/get-user called with 2 args, but it is only known to take one of the following args: []  [params]  [db params options & command-options]
This 3rd argument(options) is an optional hashmap of HugSQL-specific options (e.g., <code>:quoting</code> and <code>:adapter</code>)
Reference: https://github.com/layerware/hugsql/blob/master/docs/hugsql.org/index.html#L301
It is trivial but it removes the warnings when running the tests + fixes `lein eastwood` warnings for …
=> Fix lein eastwood warning in HugSQL

resources/leiningen/new/luminus/core/test/handler_test.clj, resources/leiningen/new/luminus/db/test/db/core_test.clj, src/leiningen/new/db.clj, src/leiningen/new/luminus.clj
for easier switching/cycling between impl and test namespaces in emacs/projectile.
I'm using this feature of Projectile/emacs pretty frequently in my non-Clojure projects
and all new luminus installations start with renaming existing test namespaces to make this function work seamlessly with default projectile settings.
`projectile-toggle-between-implementation-and-test` (SPC p a in default spacemacs settings)
I don't have much experience of using other editors/IDEs, but I suspect this change shouldn't degrade the experience or could even enhance it.
=> Rename test namespaces

resources/leiningen/new/luminus/core/src/formats.clj, resources/leiningen/new/luminus/core/src/middleware.clj
These requires seem to use `:as` aliases, but are never used.
=> Remove unused requires

resources/leiningen/new/luminus/reagent/src/cljs/core.cljs
got a warning: "Cannot infer target type in expression (. event -token)" on recompile -> looked at https://clojurescript.org/guides/externs
------
to get rid of the warning use this fix
or set this in your file
```(set! *warn-on-infer* false)```
=> get rid of type infer warning

resources/leiningen/new/luminus/core/src/core.clj
Hi maintainers, this is a follow up for the [issue](https://github.com/luminus-framework/luminus/issues/277) I opened several days ago in `luminus`, where the environment variable `IP` prevented connection to `localhost:3000` in a fresh template.
I've added the `select-keys` and verified manually that it doesn't break any of:
```
lein new luminus app
lein new luminus app +immutant
lein new luminus app +aleph
lein new luminus app +undertow
```
and that it works with `lein new luminus app +http-kit` even though I've got the `IP` environment variable set.
Please let me know if you'd like to add or change anything.
=> Added select keys to http start

resources/leiningen/new/luminus/core/env/dev/clj/user.clj
This fixes https://github.com/luminus-framework/luminus/issues/247.
=> Fix *ns* object binding in user/restart-db

resources/leiningen/new/luminus/calva/server-connect-sequence-fragment.json
Ensure user ns when Calva starts the server as part of the connect sequence.
=> Fix broken Calva config causing the server start code to fail

resources/leiningen/new/luminus/reframe/src/cljs/core.cljs
This way the nav-link properly gets the :is-active class where appropriate
=> For the nav-link, subscribe to :common/page-id

resources/leiningen/new/luminus/cljs/resources/html/home.html
The lein-shadow plugin was removed from the template, but the information page for starting the cljs development process still referenced it. 
This was clarified in #532
=> Suggest running 'shadow-cljs watch app' instead of 'lein shadow watch app'

resources/leiningen/new/luminus/calva/server-connect-sequence-fragment.json, resources/leiningen/new/luminus/calva/shadow-settings.json, resources/leiningen/new/luminus/shadow/shadow-cljs.edn
I've updated the Client + Server jack-in configuration to plain shadow-cljs.
I also changed the shadow-cljs config to include the Leiningen project's dev profile.
=> Update Calva config from lein-shadow to shadow-cljs project type

resources/leiningen/new/luminus/ctmx/src/home.clj, src/leiningen/new/ctmx.clj, src/leiningen/new/luminus.clj, test/test_templates.clj
Thanks for the great library, luminus is my go-to template.  Are you willing to add a +ctmx option for [ctmx](https://github.com/whamtet/ctmx)?  This PR add a single simple command line option which runs just after reitit.  It replaces the reitit generated `view/home.clj` with a very simple ctmx sample.  The sample is put into a single ns to show the simplicity of ctmx, am happy to adjust as per your suggestions.
=> Added +ctmx option

resources/leiningen/new/luminus/core/env/dev/resources/logback.xml, resources/leiningen/new/luminus/core/gitignore, resources/leiningen/new/luminus/db/docs/crux_instructions.md, resources/leiningen/new/luminus/db/docs/xtdb_instructions.md, resources/leiningen/new/luminus/db/src/xtdb.clj, resources/leiningen/new/luminus/db/test/db/xtdb_test.clj, src/leiningen/new/db.clj, src/leiningen/new/luminus.clj
Hi Dmitri, here's a bit of renaming following the recent crux -> XTDB rename.
Considered leaving the old `+crux`option as well for backwards compatibility but decided against it. Happy to do that though if you think it make sense.
I also noticed that we were missing the +crux option in the readme - think I might have left that out last time as I wasn't sure about the luminusdiff link. Would you be able to add that in please if/when it's released? Thanks!
=> Rename crux -> xtdb

src/leiningen/new/re_frame.clj
Re-frisk update for incompatibility with `shadow-cljs > 2.15.13` 
https://github.com/flexsurfer/re-frisk/pull/67
=> Updated re-frisk dependency

CHANGES.md, README.md, project.clj, resources/leiningen/new/luminus/core/dev-config.edn, resources/leiningen/new/luminus/core/env/dev/clj/dev_middleware.clj, resources/leiningen/new/luminus/core/env/dev/resources/config.edn, resources/leiningen/new/luminus/core/env/prod/resources/config.edn, resources/leiningen/new/luminus/core/gitignore, resources/leiningen/new/luminus/core/src/core.clj, resources/leiningen/new/luminus/core/src/middleware.clj, resources/leiningen/new/luminus/core/test-config.edn, resources/leiningen/new/luminus/reitit/src/handler-fragment.clj, resources/leiningen/new/luminus/reitit/src/home.clj, src/leiningen/new/async.clj, src/leiningen/new/expanded.clj, src/leiningen/new/logback.clj, src/leiningen/new/luminus.clj, src/leiningen/new/shadow_cljs.clj, src/leiningen/new/undertow.clj, src/leiningen/new/war.clj
closes #571
There is an async feature now that switches the server into async mode.  It also provides a utility middleware to make async handlers less painful, plus an example.
The general purpose middleware can all handle 1 and 3 arguments now, this is not tied to any feature.
I also pulled in funcool/promesa for the feature.  Programming with callbacks is not fun, promesa is fun AND cool.  It says so in the name, right?
While testing I also ran lein ancient a bunch, and I bumped whatever was outdated.
The selmer bump seems to have accidentally fixed #572
=> Support for async ring handlers

resources/leiningen/new/luminus/expanded/resources/css/screen.css
The [material icons](https://github.com/marella/material-icons) changed the names of the icon files in version 0.7.0 (see the [release notes](https://github.com/marella/material-icons/releases/tag/v0.7.0)). 
- The `eot` and the `ttf` font files were removed
-  The `woff2` and `woff` font files were renamed (`MaterialIconsOutlined-Regular` → `material-icons-outlined`)
Since Luminus depends on material-icons version 1.10.8 I think it is safe to change the css.
=> Fix asset path name to material fonts
