luminus-framework/luminus-template

src/leiningen/new/luminus/dailycred/templates/registration.html
src/leiningen/new/luminus/site/templates/base.html
src/leiningen/new/luminus/site/templates/profile.html
src/leiningen/new/luminus/site/templates/registration.html

#94 remove extra "templates/" from site and dailycred template html files

---

src/leiningen/new/cucumber.clj
src/leiningen/new/luminus/core/project.clj
src/leiningen/new/luminus/cucumber/src/browser.clj
src/leiningen/new/luminus/cucumber/src/home_page_steps.clj

This also fixes the generated artifacts for cucumber

Update lein-cucumber plugin version to latest

---

README.md
src/leiningen/new/luminus.clj
src/leiningen/new/luminus/core/project.clj
src/leiningen/new/luminus/sassc/resources/scss/screen.scss
src/leiningen/new/sassc.clj

This appears to work but could use some feedback on how to properly indent the parameters. 
My first clojure code so feedback welcome.

Add SCSS/SASS support using lien-sassc plugin.

---

src/leiningen/new/luminus/db/docs/db_instructions.md

Fix namespace name in db instructions: schema -> core

---

src/leiningen/new/luminus/core/src/middleware.clj

fixed typo in a comment

---

src/leiningen/new/db.clj
src/leiningen/new/luminus/core/gitignore
src/leiningen/new/luminus/core/project.clj
src/leiningen/new/luminus/core/src/core.clj
src/leiningen/new/luminus/db/docs/db_instructions.md
src/leiningen/new/luminus/db/docs/h2_instructions.md
src/leiningen/new/luminus/db/profiles.clj
src/leiningen/new/luminus/db/src/mongodb.clj
src/leiningen/new/luminus/db/src/mysql.db.clj
src/leiningen/new/luminus/db/src/postgres.db.clj

Related to: https://groups.google.com/forum/#!topic/luminusweb/rRJYbyUOKAY
After this change has been reviewed and/or accepted, I plan on working on a more seamless integration with Heroku and other places where the standard non-jdbc URLs are used as well as documenting the new way of using ragtime and configuring the database.

Read database configuration from profiles.clj, even for ragtime.

---

src/leiningen/new/luminus/core/src/core.clj
src/leiningen/new/luminus/core/src/handler.clj

Currently, new routes don't get reloaded when developing with ```lein figwheel```.

make wrap-reload available through figwheel as well

---

src/leiningen/new/luminus/core/project.clj
src/leiningen/new/luminus/db/src/h2.db.clj
src/leiningen/new/luminus/db/src/migrations.clj
src/leiningen/new/luminus/db/src/mysql.db.clj
src/leiningen/new/luminus/db/src/postgres.db.clj

Use to-jdbc-uri to make sure the connection URI is in JDBC format

---

src/leiningen/new/kibit.clj
src/leiningen/new/luminus.clj

added support for a code analysis tool, kibit:
https://github.com/jonase/kibit

added +kibit profile

---

src/leiningen/new/cucumber.clj

I updated the version for the lein-cucumber plugin, cucumber dependency, and selenium dependencies.

update cucumber versions

---

resources/leiningen/new/luminus/db/src/mongodb.clj

as per lines 42,43 of https://github.com/luminus-framework/luminus-template/blob/master/src/leiningen/new/db.clj

fix bug: corrected env key for :database-url

---

resources/leiningen/new/luminus/cljs/env/dev/clj/figwheel.clj
resources/leiningen/new/luminus/core/env/dev/clj/user.clj
resources/leiningen/new/luminus/core/project.clj
src/leiningen/new/cljs.clj

I am not too familiar with lein templating and some of this tooling, so there may be a mistake here. But it appears to work from what I tested.

add ability to use figwheel and a cljs repl through NRepl

---

resources/leiningen/new/luminus/core/Procfile

fixes uberjar path in Procfile

---

resources/leiningen/new/luminus/cucumber/resources/index_page.feature

- Wrong Selmer tag was in place.

Fixes generated cucumber feature

---

README.md

These are the following profile hints which are not yet documented:
`+common`
`+immutant`
`+kibit`
`+log4j`

Adds profile hints to README, fixes year on copyright license

---

resources/leiningen/new/luminus/db/src/sql.db.clj

The initial code gave me reflection warnings.

Type hinted #'<<project>>.db.core/to-date

---

project.clj
resources/leiningen/new/luminus/core/src/middleware.clj
src/leiningen/new/auth_jwe.clj
src/leiningen/new/luminus.clj

Wanted to re-start the JWT conversation with PR. Based on [buddy-auth example](https://github.com/funcool/buddy-auth/tree/master/examples/jwe). Happy to tweak as necessary. Thanks for the great template.

+auth-jwe option with basic dependencies

---

resources/leiningen/new/luminus/db/src/datomic.clj
src/leiningen/new/auth_jwe.clj

Fixed incorrect binding

---

resources/leiningen/new/luminus/reframe/src/cljs/core.cljs
src/leiningen/new/re_frame.clj

This isn't ready for merging until re-frame 0.9.0 comes out.

Update for re-frame 0.9.0

---

resources/leiningen/new/luminus/core/project.clj

Follow description in: https://github.com/technomancy/leiningen/blob/7414f61f304e1c43d209b64a1f8e739f60465ead/sample.project.clj#L300

Move test code directory into :test-paths

---

src/leiningen/new/db.clj

Bumped up monger (3.1.0)
https://github.com/michaelklishin/monger/releases/tag/v3.1.0
https://clojars.org/com.novemberain/monger

bumped up monger

---

resources/leiningen/new/luminus/core/src/core.clj
src/leiningen/new/db.clj

Adding this to have an easy way to run init scripts.

added run init case

---

resources/leiningen/new/luminus/cljs/templates/home.html
resources/leiningen/new/luminus/core/resources/templates/base.html

Unify case of HTML tag

---

resources/leiningen/new/luminus/core/env/dev/resources/logback.xml
resources/leiningen/new/luminus/core/env/prod/resources/logback.xml

I tweaked the formatting of the logback.xml template to remove the extra newline lines on different profile combinations. Just tested it, it should render properly now.

Tweaked formatting of logback.xml to remove extra newlines.

---

README.md

If you are amenable to listing the "competition", I've added links to a few similar templates.

List some alternative templates

---

resources/leiningen/new/luminus/core/build.boot

Fix boot figwheel not reloading (#329)

---

resources/leiningen/new/luminus/keeframe/src/cljs/core.cljs
resources/leiningen/new/luminus/keeframe/src/cljs/routing.cljs

Did not test this yet, as I didn't check how to. Will do now. But the change is fairly trivial.

Generate urls using hash

---

resources/leiningen/new/luminus/core/resources/html/base.html

HTML5 simplification.

---

src/leiningen/new/cljs.clj

put figwheel server log under log directory.

put figwheel server log under log directory.

---

resources/leiningen/new/luminus/compojure/src/handler-fragment.clj

indentation

---

resources/leiningen/new/luminus/reitit/src/handler-fragment.clj
resources/leiningen/new/luminus/reitit/src/services.clj

Made the `+swagger` options to use the latest reitit bundled middleware & options in order to get people started easier (including coercion). Added some samples on coercion & file handling. Related: https://github.com/metosin/reitit/issues/189

More complete example with coercion in place

---

resources/leiningen/new/luminus/core/env/dev/clj/user.clj

Makes it easier for beginners to know what's going on and is best practice to document namespaces and functions anyway.

docs: add docstrings for user namespace functions

---

project.clj
src/leiningen/new/auth_jwe.clj
src/leiningen/new/cljs.clj
src/leiningen/new/common.clj
src/leiningen/new/db.clj
src/leiningen/new/immutant.clj
src/leiningen/new/kibit.clj
src/leiningen/new/luminus.clj
src/leiningen/new/reagent.clj
src/leiningen/new/sassc.clj
src/leiningen/new/shadow_cljs.clj
src/leiningen/new/site.clj
src/leiningen/new/war.clj

I was going to do the same for `resources`, but I don't think its so straightforward because of all the `if`s that might change the formatting. I may try it again though.

Fix formatting for src

---

resources/leiningen/new/luminus/db/src/sql.db.clj
src/leiningen/new/db.clj

Fix: Could not locate clj_time/jdbc__init.class on application start

---

README.md

Since it's just the new name for maintained version:
https://www.reddit.com/r/Clojure/comments/6upzgf/general_consensus_on_fulcro/dlvym7d/
https://github.com/fulcrologic/fulcro/commit/1542e6e3c0981d9dc4d2863b8211de9db62bc686

docs: consolidate fulcro with untangled

---

README.md
resources/leiningen/new/luminus/core/env/dev/resources/logback.xml
resources/leiningen/new/luminus/core/src/core.clj
resources/leiningen/new/luminus/core/src/middleware.clj
src/leiningen/new/boot.clj
src/leiningen/new/immutant.clj
src/leiningen/new/luminus.clj
src/leiningen/new/undertow.clj

@yogthos can you verify the boot config is correct? I didn't understand too well what's happening there

add undertow profile

---

resources/leiningen/new/luminus/core/README.md
resources/leiningen/new/luminus/core/dev-config.edn.sample
resources/leiningen/new/luminus/core/test-config.edn.sample

To ease use and understanding for new Luminus template users
Resolves #482

build: include sample configuration files and documentation

---

README.md

docs: show latest Clojars badge in Readme

---

README.md

I'm sorry if it gets annoying with me sending typo fixes :D
I was just playing with various lein template options.. and noticed a few possible improvements.

Fix some typos and improve formatting

---

README.md

Related issue https://github.com/luminus-framework/luminus-template/issues/499

Add (diff) links for install options comparing

---

README.md

This diff is rather hard to review due to long lines so perhaps it is easier to review it visually at
https://github.com/nfedyashev/luminus-template/tree/experimenting-with-tables-in-readme

Use table for better readability of profile hints

---

src/leiningen/new/luminus.clj

Add cider-nrepl as dev dependency

---

resources/leiningen/new/luminus/shadow/package.json

Update npm shadow-cljs package

---

resources/leiningen/new/luminus/core/project.clj
src/leiningen/new/luminus.clj

Self-explanatory, would much appreciate if the default left a more up-to-date experience, otherwise people can get a bad impression or report already-fixed bugs.
Cheers - V

Bump Eastwood
